#!/bin/bash

while getopts ":f:t:" opt; do
  case $opt in
    f) csv_file="$OPTARG"
    ;;
    t) token="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 99; }
{
    read
    while IFS=, read -r game_id team_id name table_number team_hash team_hash_login aws_account_id status
    do
        unset AWS_SESSION_TOKEN
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_ACCESS_KEY_ID 
        
        fed_login=$(curl -H 'Accept: application/json' -H "Authorization: Bearer ${token}" https://api.eventengine.run/games/${game_id}/teams/${team_id}/sign-in-url?type=team)
        credentials=$(echo $fed_login | jq ' .credentials')

        export AWS_ACCESS_KEY_ID=`echo $credentials | jq -r ' ."access-key"'`
        export AWS_SECRET_ACCESS_KEY=`echo $credentials | jq -r ' ."secret-key"'`
        export AWS_SESSION_TOKEN=`echo $credentials | jq -r ' ."session-token"'`
        export AWS_DEFAULT_REGION=us-west-2

        instance_id=$(aws ec2 describe-instances --filters Name=image-id,Values=ami-05f091d3ff4113110,ami-0433265c8b987b1a0 | jq -r ' .Reservations | first | .Instances | first | .InstanceId')
        instance_profile=$(aws iam list-instance-profiles | jq -r ' .InstanceProfiles[] | select( .InstanceProfileName | contains("Cloud9")) | .InstanceProfileName')

        aws ec2 associate-iam-instance-profile --instance-id $instance_id --iam-instance-profile Name=$instance_profile
    done
} < $csv_file